import 'package:flutter/material.dart';
import 'package:katalog_toko/constants.dart';

class Hijab {
  final String image, title, description;
  final int price, size, id;
  final Color color;

  Hijab({
    required this.id,
    required this.image,
    required this.title,
    required this.price,
    required this.description,
    required this.size,
    required this.color,
  });
}

List<Hijab> hijabs = [
  Hijab(
    id: 1,
    title: "Aathifah Scarf",
    price: 71250,
    size: 12,
    description: "dummyText",
    image: "assets/images/aathifahScarf.png",
    color: Color(0xFFD81B60),
  ),
  Hijab(
    id: 2,
    title: "Aeesha Khimar",
    price: 57000,
    size: 12,
    description: "dummyText",
    image: "assets/images/aeeshaKhimar.png",
    color: Color(0xFF795548),
  ),
  Hijab(
    id: 3,
    title: "Bella Square",
    price: 125000,
    size: 12,
    description: "dummyText",
    image: "assets/images/bellaSquare.png",
    color: Color(0xFFF8BBD0),
  ),
  Hijab(
    id: 4,
    title: "Bergo Baby",
    price: 68000,
    size: 12,
    description: "dummyText",
    image: "assets/images/bergoBaby.png",
    color: Color(0xFFFF8A65),
  ),
  Hijab(
    id: 5,
    title: "Crinkle Shawl",
    price: 75110,
    size: 12,
    description: "dummyText",
    image: "assets/images/crinkleShawl.png",
    color: Color(0xFFAFB42B),
  ),
  Hijab(
    id: 6,
    title: "Diamond Scarf",
    price: 141500,
    size: 12,
    description: "dummyText",
    image: "assets/images/diamondScarf.png",
    color: Color(0xFFBCAAA4),
  ),
  Hijab(
    id: 7,
    title: "Jeehan Khimar",
    price: 150000,
    size: 12,
    description: "dummyText",
    image: "assets/images/jeehanKhimar.png",
    color: Color(0xFF827717),
  ),
  Hijab(
    id: 8,
    title: "Khadijah Bergo",
    price: 90250,
    size: 12,
    description: "dummyText",
    image: "assets/images/khadijahBergo.png",
    color: Color(0xFFD7CCC8),
  ),
  Hijab(
    id: 9,
    title: "Pashmina Ceruty",
    price: 120000,
    size: 12,
    description: "dummyText",
    image: "assets/images/pashminaCeruty.png",
    color: Color(0xFFF0F4C3),
  ),
  Hijab(
    id: 10,
    title: "Pashmina Plisket",
    price: 99900,
    size: 12,
    description: "dummyText",
    image: "assets/images/pashminaPlisket.png",
    color: Color(0xFF4DD0E1),
  ),
  Hijab(
    id: 11,
    title: "Segiempat Instan",
    price: 150000,
    size: 12,
    description: "dummyText",
    image: "assets/images/segiempatInstan.png",
    color: Color(0xFFFBE9E7),
  ),
  Hijab(
    id: 12,
    title: "Segiempat Lasercut",
    price: 90250,
    size: 12,
    description: "dummyText",
    image: "assets/images/segiempatLasercut.png",
    color: Color(0xFFC62828),
  ),
  Hijab(
    id: 13,
    title: "Thisa Simple Ped",
    price: 120000,
    size: 12,
    description: "dummyText",
    image: "assets/images/thisaSimplePed.png",
    color: Color(0xFFB2DFDB),
  ),
  Hijab(
    id: 14,
    title: "Zareena Bergo",
    price: 99900,
    size: 12,
    description: "dummyText",
    image: "assets/images/zareenaBergo.png",
    color: Color(0xFF546E7A),
  ),
];
