import 'package:flutter/material.dart';
import 'package:katalog_toko/constants.dart';

class Product {
  final String image, title, description, size, colorType;
  final int price, id;
  final Color color;
  Product({
    required this.id,
    required this.image,
    required this.title,
    required this.price,
    required this.description,
    required this.size,
    required this.colorType,
    required this.color,
  });
}

List<Product> products = [
  Product(
    id: 1,
    title: "Mukena Rayon",
    price: 71250,
    size: "S, M, L",
    description: "dummyText",
    image: "assets/images/mukenaRayon.png",
    color: Color(0xFFF06292),
    colorType: "Cream, Tosca, Pink,\n Merah, Ungu",
  ),
  Product(
    id: 2,
    title: "Mukena Jumbo Hyget",
    price: 57000,
    size: "Allsize fit to XL",
    description: "dummyText",
    image: "assets/images/mukenaJumbo.png",
    color: Color(0xFFD7CCC8),
    colorType: "Lavender, Maroon, Putih,\n Navy, Kunyit",
  ),
  Product(
    id: 3,
    title: "Mukena Katun Rosella",
    price: 125000,
    size: "S, M, L",
    description: "dummyText",
    image: "assets/images/mukenaKatunRosella.png",
    color: Color(0xFFB9F6CA),
    colorType: "Grey, White, Khaky,\n Maroon, Brown",
  ),
  Product(
    id: 4,
    title: "Mukena Katun Tie Dye",
    price: 68000,
    size: "S, M, L",
    description: "dummyText",
    image: "assets/images/mukenaKatunTieDye.png",
    color: Color(0xFF80D8FF),
    colorType: "Tosca, Maroon, Salem,\n Coksu",
  ),
  Product(
    id: 5,
    title: "Mukena Renda Rajut",
    price: 75110,
    size: "S, M, L",
    description: "dummyText",
    image: "assets/images/mukenaRenda.png",
    color: Color(0xFFFF4081),
    colorType: "Salem, Rouge, Ice blue,\n Light brown, Navy",
  ),
  Product(
    id: 6,
    title: "Mukena Fatimah Khadijah",
    price: 141500,
    size: "S, M, L",
    description: "dummyText",
    image: "assets/images/mukenaFatimah.png",
    color: Color(0xFFD50000),
    colorType: "Maroon, Mocca, Greentea,\n Putih",
  ),
  Product(
    id: 7,
    title: "Mukena Shireen Renda",
    price: 150000,
    size: "S, M, L",
    description: "dummyText",
    image: "assets/images/mukenaShireen.png",
    color: Color(0xFFFFA726),
    colorType: "Grey, Emerald, Navy,\n Hitam, Coksu",
  ),
  Product(
    id: 8,
    title: "Mukena Bordir Renda",
    price: 90250,
    size: "S, M, L",
    description: "dummyText",
    image: "assets/images/mukenaBordir.png",
    color: Color(0xFF795548),
    colorType: "Bordir Coklat, Bordir Turkis,\n Bordir Biru",
  ),
  Product(
    id: 9,
    title: "Mukena Anak / Rayon",
    price: 120000,
    size: "S, M, L",
    description: "dummyText",
    image: "assets/images/mukenaAnak1.png",
    color: Color(0xFF43A047),
    colorType: "Terracotta, Army, Nude,\n Hijau Mint",
  ),
  Product(
    id: 10,
    title: "Mukena Anak Daydream",
    price: 99900,
    size: "S, M, L",
    description: "dummyText",
    image: "assets/images/mukenaAnak2.png",
    color: Color(0xFF42A5F5),
    colorType: "Lilac, Biru, Pink,\n Greentea, Peach",
  ),
];
